### ISSUE TITLE
user:  Build pyMGM

### ISSUE THREAD

**Issue by paulvxx** [cs481-ekh/s24-meshers#15]
As a [Developer], I want to be able to build the pyMGM project

## Definition of Done
- [ ] I should be able to build the project from scratch into a package
- [ ] I should be able to clean project build files and re-build the project
- [ ] I should be able to run a test script to test sample input data, and compare it against expected results

## Tasks
- [ ] Build a simple python package with some basic starter code (can be irrelevant to the project)
- [ ] Set up a test folder (which should contain a python file) to ensure that your starter code can be imported and works
