### ISSUE TITLE
user: Integrate C++ libraries into Python

### ISSUE THREAD

**Issue by paulvxx** [cs481-ekh/s24-meshers#18]
As a developer, I need to be able to hook the C++ libraries and functions into Python so that we can access them

## Definition of Done
- [ ] I should be able to understand the Cpp procedures and test them out in Python
- [ ] The Cpp library calls should have the same output in Python as they would when used in MatLab

## Tasks
- [ ]  Push all relevant C files (from Dr. Wright's repository) to our repository into appropriate folders. 
- [ ] I need to find a python module/package which can bind C++ code into Python.
