### ISSUE TITLE
user: Project Structure Set Up

### ISSUE THREAD

**Issue by seanbsu** [cs481-ekh/s24-meshers#19]
As a developer, I want to set up the project's structure, so that when the time comes to add it to pyPI for a pip install it is in the correct format.

## Definition of Done
- [ ] The file structure of the project should be set up according to the requirements for pyPI
- [ ] file structure should be set up similarly to the current mgm  file structure
- [ ] (Optional if Time) set up a container for virtualization 

## Tasks
- [ ] given the file structure the top level folder should be called pymgm 
- [ ]  given the top level pymgm folder the subfolders should be set up similar to the current mgm
- [ ] given time a container image should be created with all the necessary dependencies (python version, libraries,etc) to develop the project on
