### ISSUE TITLE
user: Set up Github Actions

### ISSUE THREAD

**Issue by seanbsu** [cs481-ekh/s24-meshers#20]
As a developer, I want to set up github actions , so that I can build and test the product before integration

## Definition of Done
- [ ] there should be a github action for building and running the tests for the application
- [ ] There should be a github action for publishing the package on a release

## Tasks
- [ ] github action file properly configured to build and test the application, given a pull request when the request is made  then the script should run and tests should run and results should appear in the github action page before making the PR
- [ ] github action file properly configured to publish the package on release . When a release is made the script should run, then I should be able to install using pip install pymgm

**Comment by seanbsu** [comment]
tidying up completed user stories
