### ISSUE TITLE
user: Implement the abstract mgm class

### ISSUE THREAD

**Issue by seanbsu** [cs481-ekh/s24-meshers#49]
As a developer, I want to port over the mgm abstract class to Python, so that I can use it to create the mgm models

## Definition of Done
- [ ] All implemented functions for the abstract class have been ported
- [ ]all implemented functions in the class have been thoroughly tested.

## Tasks
- [ ] port over the abstract class
- [ ] condense the files in the mgm folder by adding the functions to the abstract class file\
- [ ] write tests for each implemented function
