### ISSUE TITLE
user: 2d class

### ISSUE THREAD

**Issue by seanbsu** [cs481-ekh/s24-meshers#78]
As a Delevloper, I want to create the mgm2d class, so that I can create a mgm object to solve a system of equations
## Definition of Done
- [ ] class is created with all necessary functions
- [ ] class inherits functions from the abstract class
- [ ] all class functions are implemented and tested

## Tasks
- [ ] create the class skeleton with all instance variables initialized
- [ ] incorporate completed constructor and interop functions into the class
- [ ] test class for proper functionality
